### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [luratic/Clarity#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text argument and return a URI Encoded string. You should use this method on id when generating the url
const trackingUrl = 'https://www.clarity.ms/tag/' + id ;

**Comment by luratic-devs** [comment]
Many thanks  @praveena-pappu. 
One question, We change the username on Github. How could we go about updating in Google Tag Manager Gallery?
