### ISSUE TITLE
Error in sessionId variable

### ISSUE THREAD

**Issue by jreidel** [luratic/Clarity#2]
In this code, sessionId refer to wrong variable (should be session_id):

`if ( addCustomIdentifiers) {
  const userId = data.user_id;
  const sessionId = data.user_id;
  const pageId = data.page_id;  
  clarity("identify", userId, sessionId, pageId);
}`

**Comment by luratic-devs** [comment]
Sorry for the delay. It has been corrected and the custom event functionality has also been added.
